Update master.py
If 'dynamics' is not mentioned here, an error appears while running the example "run_bands.py"

File "/Users/vladislavnikolaev/Desktop/aiida/aiida-vasp/lib/python3.8/site-packages/aiida/engine/processes/ports.py", line 211, in serialize
    raise TypeError(f'port namespace `{port_name}` received `{type(mapping)}` instead of a dictionary')
TypeError: port namespace `inputs.dynamics` received `<class 'aiida.orm.nodes.data.dict.Dict'>` instead of a dictionary